import Navbar from "../Navbar/Navbar";
import Footer from "../footer/Footer";
import term from "./terms.module.css";
function Terms() {
  window.scrollTo(0, 0);

  return (
    <div className={term.cont}>
      <section className="container" dir="ltr">
        <h3>1 Introduction.</h3>
        Welcome to Lifetime opportunity. Lifetime opportunity (“us”, “we”, or “our”) operates
        <a href="https://business-cards-alaa.netlify.app/"> https://business-cards-alaa.netlify.app/</a> (hereinafter referred to as
        “Service”). Our Privacy Policy governs your visit to
        <a href="https://business-cards-alaa.netlify.app/"> https://business-cards-alaa.netlify.app/</a>, and explains how we collect,
        safeguard and disclose information that results from your use of our
        Service. We use your data to provide and improve Service. By using
        Service, you agree to the collection and use of information in
        accordance with this policy. Unless otherwise defined in this Privacy
        Policy, the terms used in this Privacy Policy have the same meanings as
        in our Terms and Conditions. Our Terms and Conditions (“Terms”) govern
        all use of our Service and together with the Privacy Policy constitutes
        your agreement with us (“agreement”).
        <h3>2 Definitions.</h3>
        SERVICE means the <a href="https://business-cards-alaa.netlify.app/"> https://business-cards-alaa.netlify.app/</a> website operated
        by Lifetime opportunity. PERSONAL DATA means data about a living individual who
        can be identified from those data (or from those and other information
        either in our possession or likely to come into our possession). USAGE
        DATA is data collected automatically either generated by the use of
        Service or from Service infrastructure itself (for example, the duration
        of a page visit). COOKIES are small files stored on your device
        (computer or mobile device). DATA CONTROLLER means a natural or legal
        person who (either alone or jointly or in common with other persons)
        determines the purposes for which and the manner in which any personal
        data are, or are to be, processed. For the purpose of this Privacy
        Policy, we are a Data Controller of your data. DATA PROCESSORS (OR
        SERVICE PROVIDERS) means any natural or legal person who processes the
        data on behalf of the Data Controller. We may use the services of
        various Service Providers in order to process your data more
        effectively. DATA SUBJECT is any living individual who is the subject of
        Personal Data. THE USER is the individual using our Service. The User
        corresponds to the Data Subject, who is the subject of Personal Data.
        <h3>3. Information Collection and Use</h3>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
        <h3>4. Retention of Datad</h3>
        We will retain your Personal Data only for as long as is necessary for
        the purposes set out in this Privacy Policy. We will retain and use your
        Personal Data to the extent necessary to comply with our legal
        obligations (for example, if we are required to retain your data to
        comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies. We will also retain Usage Data for internal
        analysis purposes. Usage Data is generally retained for a shorter
        period, except when this data is used to strengthen the security or to
        improve the functionality of our Service, or we are legally obligated to
        retain this data for longer time periods.
        <h3>5. Security of Data</h3>
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While we strive to use commercially acceptable means to
        protect your Personal Data, we cannot guarantee its absolute security.
        <h3>6. Service Providers</h3>
        We may employ third party companies and individuals to facilitate our
        Service (“Service Providers”), provide Service on our behalf, perform
        Service-related services or assist us in analysing how our Service is
        used. These third parties have access to your Personal Data only to
        perform these tasks on our behalf and are obligated not to disclose or
        use it for any other purpose.
        <h3>7. Analytics</h3>
        We may use third-party Service Providers to monitor and analyze the use
        of our Service.
        <h3>8. Payments</h3>
        We may provide paid products and/or services within Service. In that
        case, we use third-party services for payment processing (e.g. payment
        processors). We will not store or collect your payment card details.
        That information is provided directly to our third-party payment
        processors whose use of your personal information is governed by their
        Privacy Policy. These payment processors adhere to the standards set by
        PCI-DSS as managed by the PCI Security Standards Council, which is a
        joint effort of brands like Visa, Mastercard, American Express and
        Discover. PCI-DSS requirements help ensure the secure handling of
        payment information.
        <h3>9. Children’s Privacy</h3>
        Our Services are not intended for use by children under the age of 18
        (“Child” or “Children”). We do not knowingly collect personally
        identifiable information from Children under 18. If you become aware
        that a Child has provided us with Personal Data, please contact us. If
        we become aware that we have collected Personal Data from Children
        without verification of parental consent, we take steps to remove that
        information from our servers.
        <h3>8. Changes to This Privacy Policy</h3>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page. We will
        let you know via email and/or a prominent notice on our Service, prior
        to the change becoming effective and update “effective date” at the top
        of this Privacy Policy. You are advised to review this Privacy Policy
        periodically for any changes. Changes to this Privacy Policy are
        effective when they are posted on this page.
      </section>
    </div>
  );
}
export default Terms;
